---
on:
  push:
    branches:
      - main
      - develop
  pull_request:

name: CI
jobs:
  ci:
    name: CI
    runs-on: [self-hosted, heavy]
    steps:
      - name: Install rust
        run: |
          rustup show
          rustup default ${{ env.RUST_VERSION }}
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Restore cache
        run: cache-util restore cargo_git cargo_registry
      - name: Check fmt
        run: cargo fmt -- --check
      - name: Lint checker
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build contract
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Test
        run: cargo test --all
      - name: Save cache
        run: |
          cache-util save cargo_git cargo_registry

env:
  RUST_VERSION: 1.72.0
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
