---
on:
  push:
    branches:
      - main
      - develop
  pull_request:

name: Lints
jobs:
  lints:
    name: Format
    runs-on: [self-hosted, light]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Run cargo fmt
        run: cargo fmt -- --check
      - name: Run Contract cargo lint checker
        run: cargo clippy --all-features -- -D warnings
      - name: Run Contract tests cargo lint checker
        run: cargo clippy --all-features --tests -- -D warnings
