---
on:
  push:
    branches:
      - master
      - develop
  pull_request:

name: Tests
jobs:
  test:
    name: Test suite (mainnet)
    runs-on: [self-hosted, heavy]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Build mainnet test WASM
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Test mainnet
        run: cargo test --all

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
